version: '3.3'
# https://docs.docker.com/compose/compose-file/

services:

################################################################################
# Elasticsearch
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
################################################################################

  es_n1:
    hostname: es_n1
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - mode: host
        target: 9200
        published: 9200
      - mode: host
        target: 9300
        published: 9300
    networks:
      - esnet1
    environment:
      - node.name=es_n1
      - cluster.name=es-cluster1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - discovery.zen.ping.unicast.hosts=es_n5,es_n4,es_n3,es_n2
      - discovery.zen.minimum_master_nodes=3
      - xpack.security.audit.enabled=true # https://www.elastic.co/guide/en/x-pack/current/auditing.html
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
      labels:
        local.description: "Elasticsearch Node 1 part of Cluster 1"
      placement:
        constraints:
          - node.labels.es.node == 1

  es_n2:
    hostname: es_n2
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - mode: host
        target: 9200
        published: 9200
      - mode: host
        target: 9300
        published: 9300
    networks:
      - esnet1
    environment:
      - node.name=es_n2
      - cluster.name=es-cluster1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - discovery.zen.ping.unicast.hosts=es_n1,es_n3,es_n4,es_n5
      - discovery.zen.minimum_master_nodes=3
      - xpack.security.audit.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
      labels:
        local.description: "Elasticsearch Node 2 part of Cluster 1"
      placement:
        constraints:
          - node.labels.es.node == 2

  es_n3:
    hostname: es_n3
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - mode: host
        target: 9200
        published: 9200
      - mode: host
        target: 9300
        published: 9300
    networks:
      - esnet1
    environment:
      - node.name=es_n3
      - cluster.name=es-cluster1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - discovery.zen.ping.unicast.hosts=es_n1,es_n2,es_n4,es_n5
      - discovery.zen.minimum_master_nodes=3
      - xpack.security.audit.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
      labels:
        local.description: "Elasticsearch Node 3 part of Cluster 1"
      placement:
        constraints:
          - node.labels.es.node == 3

  es_n4:
    hostname: es_n4
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - esdata4:/usr/share/elasticsearch/data
    ports:
      - mode: host
        target: 9200
        published: 9200
      - mode: host
        target: 9300
        published: 9300
    networks:
      - esnet1
    environment:
      - node.name=es_n4
      - cluster.name=es-cluster1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - discovery.zen.ping.unicast.hosts=es_n1,es_n2,es_n3,es_n5
      - discovery.zen.minimum_master_nodes=3
      - xpack.security.audit.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
      labels:
        local.description: "Elasticsearch Node 4 part of Cluster 1"
      placement:
        constraints:
          - node.labels.es.node == 4

  es_n5:
    hostname: es_n5
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - esdata5:/usr/share/elasticsearch/data
    ports:
      - mode: host
        target: 9200
        published: 9200
      - mode: host
        target: 9300
        published: 9300
    networks:
      - esnet1
    environment:
      - node.name=es_n5
      - cluster.name=es-cluster1
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - discovery.zen.ping.unicast.hosts=es_n1,es_n2,es_n3,es_n4
      - discovery.zen.minimum_master_nodes=3
      - xpack.security.audit.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
      labels:
        local.description: "Elasticsearch Node 5 part of Cluster 1"
      placement:
        constraints:
          - node.labels.es.node == 5


################################################################################
# Kibana
# https://www.elastic.co/guide/en/kibana/current/_configuring_kibana_on_docker.html
# https://www.elastic.co/guide/en/kibana/current/settings.html
################################################################################

  kibana_n1:
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports:
      - mode: host
        target: 5601
        published: 5601
    environment:
      SERVER_NAME: 10.75.131.12
      ELASTICSEARCH_URL: http://10.75.131.12:9200
    deploy:
      replicas: 1
      labels:
        local.description: "Kibana Node 1 part of Elasticsearch Cluster 1"
      placement:
        constraints:
          - node.labels.es.node == 1

  kibana_n2:
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports:
      - mode: host
        target: 5601
        published: 5601
    environment:
      SERVER_NAME: 10.75.131.13
      ELASTICSEARCH_URL: http://10.75.131.13:9200
    deploy:
      replicas: 1
      labels:
        local.description: "Kibana Node 2 part of Elasticsearch Cluster 1"
      placement:
        constraints:
          - node.labels.es.node == 2

################################################################################
# Docker Volumes
#
#
################################################################################

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  esdata4:
    driver: local
  esdata5:
    driver: local


################################################################################
# Docker Networks
#
#
################################################################################

networks:
  esnet1:

################################################################################

